### ISSUE TITLE
Generate Project?

### ISSUE THREAD

**Issue by clayellis** [JohnSundell/Xgen#4]
Hey @JohnSundell 👋, is the reason why there isn't a `Project` (`.xcodeproj`) `Generatable` because generating `project.pbxproj` is pretty difficult?

**Comment by JohnSundell** [comment]
Hi @clayellis 👋 That's exactly why. I would love for Xgen to be able to do that in the future though 👍

**Comment by clayellis** [comment]
I'll see what I can do about that... because I'm building some automation tools at work and man that would come in handy!
